### PR TITLE
#299 Fix participant HTTP responses to 200, 202, 409, 410

### LINKED ISSUE #299: Fix participant responses HTTP statuses to 200 (Compensated/Completed), 202 (Compensating/Completing), and 409 (FailedToCompensate/FailedToComplete)
... and distinguish the LRA participant outcome based on the HTTP message body:

* 200 + ParticipantStatus.Compensated / ParticipantStatus.Completed
* 200 + ParticipantStatus.Compensating / ParticipantStatus.Completing
* 200 + ParticipantStatus.FailedToCompensate / ParticipantStatus.FailedToComplete

### PR DESCRIPTION
**Pull request by xstefank**
resolves #299
﻿

### CODE REVIEW

File: api/src/main/java/org/eclipse/microprofile/lra/annotation/Compensate.java [hunk 1]
```diff
@@ -127,7 +127,7 @@
  *   <td scope="row">The resource does not know about the LRA</td>
  * </tr>
  * <tr>
- *   <td scope="row">500</td>
```
Comment (ochaloup) [inline api/src/main/java/org/eclipse/microprofile/lra/annotation/Compensate.java:130]: I have two points that are not major ones.
* It could be nicer if the table content would be ordered by error code. That mean the line of table with cod `409` belongs before the line with code `410`.
* As the text below says it's possible that the implementation returns the `500`. Is it obvious by the HTTP behaviour or should that code be part of the table?

Comment (xstefank) [reply api/src/main/java/org/eclipse/microprofile/lra/annotation/Compensate.java:130]: > As the text below says it's possible that the implementation returns the 500. Is it obvious by the HTTP behaviour or should that code be part of the table?

HTTP behavior, this is not a supported code returned by the implementation of LRA but the general error which can be returned from JAX-RS server (same as connection error for instance) so it shouldn't be mentioned in the table.

**Comment by xstefank** [comment]
@ochaloup can you take a look again, please?

**Comment by xstefank** [comment]
If there will be no other objections, I will merge this PR this Friday (08/14/2020).

**Comment by xstefank** [comment]
A lot of people on PTOs, extending until 08/21/2020.

**Comment by xstefank** [comment]
only rebase
